# This is a basic workflow to help you get started with Actions

name: Release
 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
     SOLUTION_PATH: src/PersonneClassLibrairy/PersonneClassLibrairy.sln
     PERSON_APP_PATH: src/PersonneClassLibrairy/PersonneClassLibrairy/PersonneClassLibrairy.csproj

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: "Checking the code"
       
      - run: | 
         git fetch --all
        name: fetching the tags
     
      - run: echo ${{github.ref_name}}
        name: "Version number"
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
        name: Setup dotnet

      - name: Restore dependencies of the solution
        run: dotnet restore $SOLUTION_PATH 
      
      - name: Build the solution
        run: dotnet build $SOLUTION_PATH   --no-restore -c release
      
      - name: Pack
        run: dotnet pack ${{env.PERSON_APP_PATH}} -c Release -p:PackageVersion=${{ github.ref_name }}

      - name: Push
        run: dotnet nuget push ${{env.PERSON_APP_PATH}}\bin\Release\PersonneClassLibrairy.${{ github.ref_name }}.nupkg -s https://nuget.pkg.github.com/angoudjou/PersonneDetail/index.json -k ${{env.GITHUB_TOKEN}} 
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}


